### ISSUE TITLE
Make a decision on the split between Edges/Kibana/Grafana

### ISSUE THREAD

**Issue by richard-jones** [NGLPteam/NGLP-Analytics#29]
The proposal discussed in our last meeting is as follows:

We should build custom visualisations to cover all reporting where end users nearer the base of the user pyramid will interact with the reports (i.e. readers, authors, editors, at least), and where the reports can most easily be presented in a "canned" form.

We should then also provide as part of the technical stack a Kibana instance with a number of pre-built dashboards for the common use cases, and the ability for the user of the Kibana to have free reign in developing their own analytics and visualisations.  This would be most suited to service operators.

@Pcolar I think this is for you to make the formal go ahead or not on the above proposal

**Comment by Pcolar** [comment]
I'm back from holiday and seeing this. Will bring the discussion to the Product Owners and post a decision.

**Comment by Pcolar** [comment]
NGLP agrees with the decision to incorporate Edges/Kibana/ Grafana under the current scheme. 
We also agree that any approaches to adopt a React framework would involve substantial redesign and is not considered viable for MVP.
