### ISSUE TITLE
Build the ES Event Store

### ISSUE THREAD

**Issue by richard-jones** [NGLPteam/NGLP-Analytics#4]
- [x] Review the models and implementation #2 and #3
- [x] Set up any required ES mappings
- [x] Build app initialisation routines to construct index with mappings
- [x] Set this up to run in a cloud environment

**Comment by richard-jones** [comment]
@Steven-Eardley I've added code to auto-generate the mapping from the object struct, and spent a bit of time with the latest ES docs to produce what I think is the right mapping.  The mapping in JSON is at the bottom of this comment.

You can see the mapping configuration here: https://github.com/NGLPteam/NGLP-Analytics/blob/develop/nglp/dao.py

and the struct that is being mapped here: https://github.com/NGLPteam/NGLP-Analytics/blob/develop/nglp/models/structs.py#L262

Could you have a look over that and review it for me, and then see if you can use that mapping to generate the ES index?

I haven't yet set up an "initialise" function, but I can do that.  Right now this code is framework free, so I haven't built anything like a Flask `create_app` function that would do any initialisation, as it's not obvious that the code will always be run as a web application.


```
{
  "properties": {
    "occurred_at": {
      "type": "date",
      "format": "dateOptionalTime"
    },
    "category": {
      "type": "text",
      "fields": {
        "exact": {
          "type": "keyword"
        }
      }
    },
    "event": {
      "type": "text",
      "fields": {
        "exact": {
          "type": "keyword"
        }
      }
    },
    "object_type": {
      "type": "text",
      "fields": {
        "exact": {
          "type": "keyword"
        }
      }
    },
    "format": {
      "type": "text",
      "fields": {
        "exact": {
          "type": "keyword"
        }
      }
    },
    "url": {
      "type": "text",
      "fields": {
        "exact": {
          "type": "keyword"
        }
      }
    },
    "method": {
      "type": "text",
      "fields": {
        "exact": {
          "type": "keyword"
        }
      }
    },
    "referrer": {
      "type": "text",
      "fields": {
        "exact": {
          "type": "keyword"
        }
      }
    },
    "user_agent": {
      "type": "text",
      "fields": {
        "exact": {
          "type": "keyword"
        }
      }
    },
    "user_id": {
      "type": "text",
      "fields": {
        "exact": {
          "type": "keyword"
        }
      }
    },
    "ip": {
      "type": "ip"
    },
    "city": {
      "type": "text",
      "fields": {
        "exact": {
          "type": "keyword"
        }
      }
    },
    "country": {
      "type": "text",
      "fields": {
        "exact": {
          "type": "keyword"
        }
      }
    },
    "object_id": {
      "type": "text",
      "fields": {
        "exact": {
          "type": "keyword"
        }
      }
    },
    "container": {
      "type": "text",
      "fields": {
        "exact": {
          "type": "keyword"
        }
      }
    },
    "search_keywords": {
      "type": "text",
      "fields": {
        "exact": {
          "type": "keyword"
        }
      }
    },
    "user_org": {
      "type": "text",
      "fields": {
        "exact": {
          "type": "keyword"
        }
      }
    },
    "share": {
      "properties": {
        "source_id": {
          "type": "text",
          "fields": {
            "exact": {
              "type": "keyword"
            }
          }
        },
        "subj_id": {
          "type": "text",
          "fields": {
            "exact": {
              "type": "keyword"
            }
          }
        }
      }
    },
    "location": {
      "type": "geo_point"
    },
    "source": {
      "properties": {
        "identifier": {
          "type": "text",
          "fields": {
            "exact": {
              "type": "keyword"
            }
          }
        },
        "type": {
          "type": "text",
          "fields": {
            "exact": {
              "type": "keyword"
            }
          }
        },
        "archive_id": {
          "type": "text",
          "fields": {
            "exact": {
              "type": "keyword"
            }
          }
        }
      }
    }
  }
}
```

**Comment by richard-jones** [comment]
I've now added a mechanism to send the mapping to the index when an `initialise` method is called.

I've also tested this by sending a small amount of test data into a local index.

There is a bit more work required to make this ready to run on a test machine - we need to adopt a framework (we have decided in FastAPI) which will give us all the config management, and then we can set this up so it can be deployed on any machine.

**Comment by Steven-Eardley** [comment]
I've successfully used this on my local machine to initialise and populate a remote test index. Mappings look great as a first pass. We can add a python dockerfile to orchestration to run this to get that last checkbox ticked.

**Comment by richard-jones** [comment]
@Steven-Eardley I see that checkbox is now ticked, does this mean we can close this issue off?

**Comment by Steven-Eardley** [comment]
This is running on elasticsearch.nglp-test.cottagelabs.com with initialisation and the generated data, the analytics app is authenticating correctly with ES. There is a dockerfile to run the analytics app, too.

Last remaining task is to include running the API in the ansible orchestration config for ease of deployment
