### ISSUE TITLE
Event test data generator

### ISSUE THREAD

**Issue by richard-jones** [NGLPteam/NGLP-Analytics#6]
- [x] Test data to go directly into the core analytics index for use in report development
- [x] Test data to go into the Event API + Test data to go into the Reporting Context for use in testing the Event API
- [x] Save the test as json objects in file

**Comment by anusharanganathan** [comment]
Write a CLI that uses the model. The args need to be
* type of event
* number of events
* filename
* generate errors?
* Output type - csv / json
Investigate faker - https://faker.readthedocs.io/en/master/

**Comment by richard-jones** [comment]
@DhileasHeywood here are the next steps for this one, I think:

1. Make sure we can generate usage data for articles and journals at least.  Leave the workflow test data generation for the moment, we can come back to it, as it's a bit complicated.

2. Install the open distro of elasticsearch locally: https://opendistro.github.io/for-elasticsearch/downloads.html#develop

3. Generate a load of test data, and then use the script in `test/load_test_data.py` to load that data into your local index.  Take a look around at it, and make sure that it looks sensible.

4. Speak to @Steven-Eardley about getting the app onto the test server, and populating the test server's index with test data.

After that we can move to developing some reports locally (#44)

**Comment by richard-jones** [comment]
@DhileasHeywood just to give you an update on some tweaks that I made to the test data generator while you were away:

* I've now customised most of the event types, so that they only contain the fields that are relevant to them.  This isn't perfect, but it's pretty good, and suitable at least for testing.  We might revisit this at some point if we want some tighter objects.
* I've limited the values of some fields (like the HTTP methods) to a subset of the full possible list, since they are more realistic (like, when has anyone ever issued an OPTIONS request!).

There is a couple of things that we need to do next to get this finished:

1. Build a model and test data generator for the Search event, which we managed to overlook on the first pass.  Most of the mechanics for it are already there, probably just need to define the event model, and wire it up to the test data generator.
2. Build a mechanism for producing workflow event test data.  I'm tempted to pull that out into a separate issue of its own, because it is going to be a bit complicated.

**Comment by richard-jones** [comment]
There is a little more work to do here on the workflow test data, so I'm going to bump this back to In Progress

**Comment by richard-jones** [comment]
Workflow test data is all now being generated, so I'm pushing this one on to review again, and probably we can close it off.  There will no doubt be tweaks to test generation as the project progresses, but I don't think we need to keep this issue open.  Will review at today's meeting and then close if agreed.
