### ISSUE TITLE
Make test installation of DSpace and populate with test data

### ISSUE THREAD

**Issue by richard-jones** [NGLPteam/NGLP-Analytics#9]
- [x] Install DSpace 7 on test infrastructure
- [x] Populate DSpace instance with test data (manually or automatically)
- [ ] Implement a mechanism to generate usage statistics (e.g. using Chromedriver to generate events)

**Comment by richard-jones** [comment]
Making some notes of useful resources here:

* Docker compose for DSpace: https://github.com/DSpace/DSpace/tree/main/dspace/src/main/docker-compose
* Demo data: https://github.com/DSpace-Labs/AIP-Files/releases/tag/demo-entities-data
* DSpace 7 Docker Hub: https://hub.docker.com/r/dspace/dspace/src/main/docker-compose/README.md
* Tutorial and video: https://wiki.lyrasis.org/display/DSPACE/Running+DSpace+7+with+Docker

**Comment by richard-jones** [comment]
Instructions I followed to install:

1. Set up Docker as per: https://docs.docker.com/engine/install/ubuntu/
2. Set up to run docker as non-root user: https://docs.docker.com/engine/install/linux-postinstall/
3. Verify install and checkout DSpace Docker Images: https://dspace-labs.github.io/DSpace-Docker-Images/documentation/setup.LinuxDesktop.html
4. Verify that I have the DSpace resources needed: https://dspace-labs.github.io/DSpace-Docker-Images/documentation/workshop/exercise1.html
5. Launch DSpace 7: https://wiki.lyrasis.org/display/DSPACE/Running+DSpace+7+with+Docker
6. See REST API: http://localhost:8080/server/#/server/api
7. See UI: http://localhost:3000/

On completion, no content immediately visible in the UI, this could be because it's still indexing.  Leaving it for a while to see.

**Comment by richard-jones** [comment]
So following the above steps did not work, there was something wrong with the DSpace setup which meant that the UI was non-functional, and the API gave incorrect URLs for the various resources.  When the urls were manually corrected they seemed to work, though, so this could just be a setup step that the docs have not covered.  I am trying some alternative compose configurations from: https://github.com/DSpace-Labs/DSpace-Docker-Images/tree/master/docker-compose-files/dspace-compose-v2#run-dspace-7x

**Comment by richard-jones** [comment]
All routes have failed to yield a way forward with docker.  I may poke at the DSpace slack next week, though Hardy has also given me access to some of his personal work on DSpace deployments with lando and/or ansible/terraform that we might be able to use.

**Comment by richard-jones** [comment]
Here are some resources that I got from Hardy that may help us get moving:

* Terraform/Ansible build: https://github.com/hardyoyo/dspace-aws-testing
* Lando dev environment: https://github.com/hardyoyo/code4lib2021-workshop/tree/master/examples/dspace

@Steven-Eardley @alexdutton can I ask you for your opinion on what the best way to go for getting a test instance up that we can play with would be?

**Comment by richard-jones** [comment]
Some DSpace 7 install guides for doing this manually:

* https://hyperlink.co.ke/2020/08/09/install-dspace-7-on-ubuntu-18-04/
* https://wiki.lyrasis.org/display/DSDOC7x/Installing+DSpace

@Steven-Eardley @alexdutton can I have your advice on whether it is sensible for us to just manually install DSpace 7 on a machine by following the manual instructions?

**Comment by Steven-Eardley** [comment]
In the interests of getting it done, I'm happy for us to manually install on a VM. Laid out on these excellent instructions it seems simple to do. To me that makes it even more frustrating that the docker images don't seem to be behaving. I'll start the process now.

**Comment by Steven-Eardley** [comment]
I've brought this up manually on a VM. Some of the pain points were CORS and SSL.

https://nglp-ds7-ui.cottagelabs.com
https://nglp-ds7.cottagelabs.com/server

Still work to do to get file uploads working, and haven't tried test data yet.

**Comment by richard-jones** [comment]
@RK206 Now that you're getting to grips with the DSpace issues for uploading files, could I ask you also to have a look at why downloading files isn't working?  For example, when I hit this URL I get a server error: https://nglp-ds7-ui.cottagelabs.com/bitstreams/d5b0e8d3-3520-4609-8e3a-c26adeaa74b9/download

**Comment by RK206** [comment]
@richard-jones You are seeing the error because there is no file available. 
The test data that we uploaded does't have files in it.

I have  created  a item and uploaded a file and I am able to open the file. 
https://nglp-ds7-ui.cottagelabs.com/entities/publication/2f0009ac-05d9-4527-9bd4-36db828c32da

**Comment by richard-jones** [comment]
A DSpace instance was set up and configured for investigation, and populated with data.  I am closing this issue as technically complete, although downstream use of that DSpace instance was never made (see #10 )
